### Mod properties
mod.name=Debug Screen Option Profiles
mod.id=debug_option_profiles
mod.version=1.0
mod.description=Adds the ability to save debug screen settings presets (F3)

### Publishing
mod.modrinth=uEiSR0ob
mod.curseforge=1252453
mod.github=stonecutter-multiloader

### Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

### Other
net.minecraftforge.gradle.merge-source-sets=true
