### Mod properties
mod.name=Debug Screen Option Profiles
mod.id=debug_option_profiles
mod.version=1.0
mod.description=Adds the ability to save debug screen settings presets (F3)

### Dependencies
# Fabric versions see: https://fabricmc.net/develop
# Forge versions see: https://files.minecraftforge.net
# NeoForge versions see: https://neoforged.net
# Cloth Config and ModMenu see: https://linkie.shedaniel.dev/dependencies

### Publishing
mod.modrinth=f9bNNo0a
mod.curseforge=1438515
mod.github=f3-profiles

### Other
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
