# Fabric versions see: https://fabricmc.net/develop
# Forge versions see: https://files.minecraftforge.net
# NeoForge versions see: https://neoforged.net

["26.2"]
pub_end="latest"

["1.21.11"]
pub_start="1.21.9"
